
version: "3.8"
services:
  ph3-posseapp-web:
    platform: linux/amd64
    build:
      context: ./container/web
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80

  ph3-posseapp-app:
    platform: linux/amd64
    build:
      context: ./container/app
    volumes:
      - ./src:/var/www/html

  ph3-posseapp-db:
    platform: linux/amd64
    build:
      context: ./container/db
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  node:
    image: node:16
    tty: true
    volumes:
      - ./src:/mnt
    working_dir: /mnt
